INSERT INTO product (title, category, brand, price, stock, description, availability)
VALUES ('Nike Air Force',
        'Calçados',
        'Nike', 299.99, 50,
        'Tênis leve e confortável.',
        'IN_STOCK'),
       ('Cortez White',
        'Calçados',
        'Nike', 899.99, 6,
        'Tênis leve e confortável.',
        'IN_STOCK'),
       ('Nike Shox TL',
        'Calçados',
        'Nike', 2299.99, 0,
        'Tênis leve e confortável.',
        'OUT_OF_STOCK'),
       ('Air Max 90',
        'Calçados',
        'Nike', 1249.99, 2,
        'Tênis leve e confortável.',
        'IN_STOCK');

INSERT INTO product (title, category, brand, price, stock, description, availability)
VALUES ('Adidas Ultraboost', 'Calçados',
        'Adidas',
        349.99,
        0,
        'Tênis leve e confortável.',
        'OUT_OF_STOCK'),
       ('Adidas Superstar',
        'Calçados',
        'Adidas',
        249.99,
        0,
        'Tênis leve e confortável.',
        'OUT_OF_STOCK'),
       ('Adidas NMD_R1',
        'Calçados',
        'Adidas',
        299.99,
        80,
        'Tênis leve e confortável.',
        'IN_STOCK'),
       ('Adidas Stan Smith',
        'Calçados',
        'Adidas',
        229.99,
        80,
        'Tênis leve e confortável.',
        'IN_STOCK');

INSERT INTO product (title, category, brand, price, stock, description, availability)
VALUES ('Nike Sportswear Club',
        'Vestuário',
        'Nike',
        199.99,
        100,
        'Blusa confortável.',
        'IN_STOCK'),
       ('Nike Dri-FIT Academy',
        'Vestuário',
        'Nike',
        149.99,
        80,
        'Blusa confortável.',
        'IN_STOCK'),
       ('Nike Therma-FIT Legacy',
        'Vestuário',
        'Nike',
        249.99,
        0,
        'Blusa confortável.',
        'OUT_OF_STOCK'),
       ('Nike Pro Long Sleeve',
        'Vestuário',
        'Nike',
        129.99,
        50,
        'Blusa confortável.',
        'IN_STOCK');

INSERT INTO product (title, category, brand, price, stock, description, availability)
VALUES ('Adidas Essentials 3-Stripes',
        'Vestuário',
        'Adidas',
        179.99,
        120,
        'Blusa confortável.',
        'IN_STOCK'),
       ('Adidas Aeroready Designed 2 Move',
        'Vestuário',
        'Adidas',
        139.99,
        90,
        'Blusa confortável.',
        'IN_STOCK'),
       ('Adidas ZNE Hoodie',
        'Vestuário',
        'Adidas',
        259.99,
        0,
        'Blusa confortável.',
        'OUT_OF_STOCK'),
       ('Adidas Game and Go',
        'Vestuário',
        'Adidas',
        159.99,
        60,
        'Blusa confortável.',
        'IN_STOCK');